# Generated by Django 6.0.5 on 2026-05-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_session_has_ended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='session',
            name='max_players',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_per_question',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
