# Generated by Django 6.0.5 on 2026-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_playeranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='has_ended',
            field=models.BooleanField(default=False),
        ),
    ]
