# Generated by Django 6.0.5 on 2026-05-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0004_alter_workspaceinvitation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='token',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
        ),
    ]
