# Generated by Django 6.0.5 on 2026-05-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_profile_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single choice'), ('multiple', 'Multiple choice'), ('text', 'Text answer')], default='single', max_length=10),
        ),
    ]
